# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'retool-settings.ui'
##
## Created by: Qt User Interface Compiler version 6.6.2
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QLayout, QPushButton,
    QSizePolicy, QSpacerItem, QWidget)

from modules.gui.custom_widgets import (CustomLineEdit, ElisionLabel)
from . import resources_rc

class Ui_Settings(object):
    def setupUi(self, Settings):
        if not Settings.objectName():
            Settings.setObjectName(u"Settings")
        Settings.resize(604, 400)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QSize(604, 400))
        Settings.setMaximumSize(QSize(604, 400))
        Settings.setAutoFillBackground(False)
        Settings.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayoutWidget = QWidget(Settings)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(-1, -1, 601, 471))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SetMinAndMaxSize)
        self.gridLayout.setVerticalSpacing(12)
        self.gridLayout.setContentsMargins(15, 15, 15, 0)
        self.lineDownloadLocations = QFrame(self.gridLayoutWidget)
        self.lineDownloadLocations.setObjectName(u"lineDownloadLocations")
        palette = QPalette()
        brush = QBrush(QColor(85, 85, 85, 255))
        brush.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        brush1 = QBrush(QColor(120, 120, 120, 255))
        brush1.setStyle(Qt.SolidPattern)
        palette.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.lineDownloadLocations.setPalette(palette)
        self.lineDownloadLocations.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.lineDownloadLocations.setFrameShadow(QFrame.Plain)
        self.lineDownloadLocations.setFrameShape(QFrame.HLine)

        self.gridLayout.addWidget(self.lineDownloadLocations, 8, 0, 1, 1)

        self.frameResetButton = QFrame(self.gridLayoutWidget)
        self.frameResetButton.setObjectName(u"frameResetButton")
        self.frameResetButton.setMinimumSize(QSize(0, 25))
        self.frameResetButton.setMaximumSize(QSize(16777215, 25))
        self.frameResetButton.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameResetButton.setFrameShape(QFrame.NoFrame)
        self.frameResetButton.setFrameShadow(QFrame.Plain)
        self.pushButtonReset = QPushButton(self.frameResetButton)
        self.pushButtonReset.setObjectName(u"pushButtonReset")
        self.pushButtonReset.setGeometry(QRect(546, 0, 25, 25))
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy1)
        self.pushButtonReset.setMinimumSize(QSize(25, 25))
        self.pushButtonReset.setMaximumSize(QSize(25, 25))
        self.pushButtonReset.setLayoutDirection(Qt.LeftToRight)
        icon = QIcon()
        icon.addFile(u":/retoolFiles/images/icons8-restart-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.pushButtonReset.setIcon(icon)
        self.pushButtonReset.setAutoDefault(False)
        self.labelSettingsSaved = QLabel(self.frameResetButton)
        self.labelSettingsSaved.setObjectName(u"labelSettingsSaved")
        self.labelSettingsSaved.setGeometry(QRect(0, 0, 381, 18))
        self.labelSettingsSaved.setMinimumSize(QSize(0, 18))
        self.labelSettingsSaved.setMaximumSize(QSize(16777215, 18))
        font = QFont()
        font.setFamilies([u"Segoe UI"])
        self.labelSettingsSaved.setFont(font)
        self.labelSettingsSaved.setScaledContents(False)
        self.labelSettingsSaved.setAlignment(Qt.AlignLeading|Qt.AlignLeft|Qt.AlignTop)
        self.labelSettingsSaved.setWordWrap(True)
        self.labelSettingsSaved.setOpenExternalLinks(True)
        self.labelSettingsSaved.setTextInteractionFlags(Qt.LinksAccessibleByKeyboard|Qt.LinksAccessibleByMouse)

        self.gridLayout.addWidget(self.frameResetButton, 0, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SetDefaultConstraint)
        self.labelCloneListMetadataDownloadURL = QLabel(self.gridLayoutWidget)
        self.labelCloneListMetadataDownloadURL.setObjectName(u"labelCloneListMetadataDownloadURL")
        self.labelCloneListMetadataDownloadURL.setMinimumSize(QSize(0, 18))
        self.labelCloneListMetadataDownloadURL.setMaximumSize(QSize(16777215, 18))
        font1 = QFont()
        font1.setFamilies([u"Segoe UI"])
        font1.setBold(False)
        self.labelCloneListMetadataDownloadURL.setFont(font1)
        self.labelCloneListMetadataDownloadURL.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout.addWidget(self.labelCloneListMetadataDownloadURL)

        self.labelURLError = QLabel(self.gridLayoutWidget)
        self.labelURLError.setObjectName(u"labelURLError")
        self.labelURLError.setMinimumSize(QSize(0, 18))
        self.labelURLError.setMaximumSize(QSize(16777215, 18))
        palette1 = QPalette()
        brush2 = QBrush(QColor(255, 0, 0, 255))
        brush2.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Active, QPalette.WindowText, brush2)
        brush3 = QBrush(QColor(0, 0, 0, 255))
        brush3.setStyle(Qt.SolidPattern)
        palette1.setBrush(QPalette.Inactive, QPalette.WindowText, brush3)
        palette1.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.labelURLError.setPalette(palette1)
        self.labelURLError.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelURLError.setAlignment(Qt.AlignRight|Qt.AlignTrailing|Qt.AlignVCenter)

        self.horizontalLayout.addWidget(self.labelURLError)


        self.gridLayout.addLayout(self.horizontalLayout, 10, 0, 1, 1)

        self.linePaths = QFrame(self.gridLayoutWidget)
        self.linePaths.setObjectName(u"linePaths")
        palette2 = QPalette()
        palette2.setBrush(QPalette.Active, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Inactive, QPalette.WindowText, brush)
        palette2.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        self.linePaths.setPalette(palette2)
        self.linePaths.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.linePaths.setFrameShadow(QFrame.Plain)
        self.linePaths.setFrameShape(QFrame.HLine)

        self.gridLayout.addWidget(self.linePaths, 2, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer, 6, 0, 1, 1)

        self.labelDownloadLocations = QLabel(self.gridLayoutWidget)
        self.labelDownloadLocations.setObjectName(u"labelDownloadLocations")
        self.labelDownloadLocations.setMinimumSize(QSize(0, 18))
        self.labelDownloadLocations.setMaximumSize(QSize(16777215, 18))
        font2 = QFont()
        font2.setFamilies([u"Segoe UI"])
        font2.setBold(True)
        self.labelDownloadLocations.setFont(font2)
        self.labelDownloadLocations.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelDownloadLocations.setTextInteractionFlags(Qt.NoTextInteraction)

        self.gridLayout.addWidget(self.labelDownloadLocations, 7, 0, 1, 1)

        self.frameQuickImportLocation = QFrame(self.gridLayoutWidget)
        self.frameQuickImportLocation.setObjectName(u"frameQuickImportLocation")
        self.frameQuickImportLocation.setMinimumSize(QSize(0, 41))
        self.frameQuickImportLocation.setMaximumSize(QSize(16777215, 41))
        self.frameQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameQuickImportLocation.setFrameShape(QFrame.NoFrame)
        self.frameQuickImportLocation.setFrameShadow(QFrame.Plain)
        self.frameQuickImportLocation.setLineWidth(0)
        self.buttonChooseQuickImportLocation = QPushButton(self.frameQuickImportLocation)
        self.buttonChooseQuickImportLocation.setObjectName(u"buttonChooseQuickImportLocation")
        self.buttonChooseQuickImportLocation.setGeometry(QRect(0, 0, 41, 41))
        font3 = QFont()
        font3.setFamilies([u"Segoe UI"])
        font3.setPointSize(10)
        self.buttonChooseQuickImportLocation.setFont(font3)
        icon1 = QIcon()
        icon1.addFile(u":/retoolFiles/images/icons8-live-folder-80.png", QSize(), QIcon.Normal, QIcon.Off)
        self.buttonChooseQuickImportLocation.setIcon(icon1)
        self.buttonChooseQuickImportLocation.setIconSize(QSize(32, 32))
        self.buttonChooseQuickImportLocation.setAutoDefault(False)
        self.labelSelectQuickImportLocation = QLabel(self.frameQuickImportLocation)
        self.labelSelectQuickImportLocation.setObjectName(u"labelSelectQuickImportLocation")
        self.labelSelectQuickImportLocation.setGeometry(QRect(50, 0, 531, 22))
        self.labelSelectQuickImportLocation.setFont(font1)
        self.labelSelectQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelQuickImportLocation = ElisionLabel(self.frameQuickImportLocation)
        self.labelQuickImportLocation.setObjectName(u"labelQuickImportLocation")
        self.labelQuickImportLocation.setGeometry(QRect(50, 20, 531, 20))
        palette3 = QPalette()
        brush4 = QBrush(QColor(119, 119, 119, 255))
        brush4.setStyle(Qt.SolidPattern)
        palette3.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette3.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette3.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette3.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette3.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        self.labelQuickImportLocation.setPalette(palette3)
        font4 = QFont()
        font4.setFamilies([u"Segoe UI"])
        font4.setPointSize(8)
        self.labelQuickImportLocation.setFont(font4)
        self.labelQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameQuickImportLocation, 5, 0, 1, 1)

        self.frameCloneListsLocation = QFrame(self.gridLayoutWidget)
        self.frameCloneListsLocation.setObjectName(u"frameCloneListsLocation")
        self.frameCloneListsLocation.setMinimumSize(QSize(0, 41))
        self.frameCloneListsLocation.setMaximumSize(QSize(16777215, 41))
        self.frameCloneListsLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameCloneListsLocation.setFrameShape(QFrame.NoFrame)
        self.frameCloneListsLocation.setFrameShadow(QFrame.Plain)
        self.frameCloneListsLocation.setLineWidth(0)
        self.buttonChooseCloneListsLocation = QPushButton(self.frameCloneListsLocation)
        self.buttonChooseCloneListsLocation.setObjectName(u"buttonChooseCloneListsLocation")
        self.buttonChooseCloneListsLocation.setGeometry(QRect(0, 0, 41, 41))
        self.buttonChooseCloneListsLocation.setFont(font3)
        self.buttonChooseCloneListsLocation.setIcon(icon1)
        self.buttonChooseCloneListsLocation.setIconSize(QSize(32, 32))
        self.buttonChooseCloneListsLocation.setAutoDefault(False)
        self.labelSelectCloneListsLocation = QLabel(self.frameCloneListsLocation)
        self.labelSelectCloneListsLocation.setObjectName(u"labelSelectCloneListsLocation")
        self.labelSelectCloneListsLocation.setGeometry(QRect(50, 0, 531, 16))
        self.labelSelectCloneListsLocation.setFont(font1)
        self.labelCloneListsLocation = ElisionLabel(self.frameCloneListsLocation)
        self.labelCloneListsLocation.setObjectName(u"labelCloneListsLocation")
        self.labelCloneListsLocation.setGeometry(QRect(50, 20, 531, 20))
        palette4 = QPalette()
        palette4.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette4.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette4.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette4.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        self.labelCloneListsLocation.setPalette(palette4)
        self.labelCloneListsLocation.setFont(font4)

        self.gridLayout.addWidget(self.frameCloneListsLocation, 3, 0, 1, 1)

        self.frameCloneListMetadataDownloadLocation = QFrame(self.gridLayoutWidget)
        self.frameCloneListMetadataDownloadLocation.setObjectName(u"frameCloneListMetadataDownloadLocation")
        self.frameCloneListMetadataDownloadLocation.setMinimumSize(QSize(0, 24))
        self.frameCloneListMetadataDownloadLocation.setMaximumSize(QSize(16777215, 24))
        self.frameCloneListMetadataDownloadLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameCloneListMetadataDownloadLocation.setFrameShape(QFrame.StyledPanel)
        self.frameCloneListMetadataDownloadLocation.setFrameShadow(QFrame.Raised)
        self.lineEditCloneListDownloadLocation = CustomLineEdit(self.frameCloneListMetadataDownloadLocation)
        self.lineEditCloneListDownloadLocation.setObjectName(u"lineEditCloneListDownloadLocation")
        self.lineEditCloneListDownloadLocation.setGeometry(QRect(0, 0, 571, 24))
        self.lineEditCloneListDownloadLocation.setMinimumSize(QSize(0, 24))
        self.lineEditCloneListDownloadLocation.setMaximumSize(QSize(16777215, 24))

        self.gridLayout.addWidget(self.frameCloneListMetadataDownloadLocation, 12, 0, 1, 1)

        self.labelPaths = QLabel(self.gridLayoutWidget)
        self.labelPaths.setObjectName(u"labelPaths")
        self.labelPaths.setMinimumSize(QSize(0, 18))
        self.labelPaths.setMaximumSize(QSize(16777215, 18))
        self.labelPaths.setFont(font2)
        self.labelPaths.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelPaths.setTextInteractionFlags(Qt.NoTextInteraction)

        self.gridLayout.addWidget(self.labelPaths, 1, 0, 1, 1)

        self.frameMetadataLocation = QFrame(self.gridLayoutWidget)
        self.frameMetadataLocation.setObjectName(u"frameMetadataLocation")
        self.frameMetadataLocation.setMinimumSize(QSize(0, 41))
        self.frameMetadataLocation.setMaximumSize(QSize(16777215, 41))
        self.frameMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameMetadataLocation.setFrameShape(QFrame.NoFrame)
        self.frameMetadataLocation.setFrameShadow(QFrame.Plain)
        self.frameMetadataLocation.setLineWidth(0)
        self.buttonChooseMetadataLocation = QPushButton(self.frameMetadataLocation)
        self.buttonChooseMetadataLocation.setObjectName(u"buttonChooseMetadataLocation")
        self.buttonChooseMetadataLocation.setGeometry(QRect(0, 0, 41, 41))
        self.buttonChooseMetadataLocation.setFont(font3)
        self.buttonChooseMetadataLocation.setIcon(icon1)
        self.buttonChooseMetadataLocation.setIconSize(QSize(32, 32))
        self.buttonChooseMetadataLocation.setAutoDefault(False)
        self.labelSelectMetadataLocation = QLabel(self.frameMetadataLocation)
        self.labelSelectMetadataLocation.setObjectName(u"labelSelectMetadataLocation")
        self.labelSelectMetadataLocation.setGeometry(QRect(50, 0, 531, 22))
        self.labelSelectMetadataLocation.setFont(font1)
        self.labelSelectMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelMetadataLocation = ElisionLabel(self.frameMetadataLocation)
        self.labelMetadataLocation.setObjectName(u"labelMetadataLocation")
        self.labelMetadataLocation.setGeometry(QRect(50, 20, 531, 20))
        palette5 = QPalette()
        palette5.setBrush(QPalette.Active, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Active, QPalette.Text, brush3)
        palette5.setBrush(QPalette.Inactive, QPalette.WindowText, brush4)
        palette5.setBrush(QPalette.Inactive, QPalette.Text, brush3)
        palette5.setBrush(QPalette.Disabled, QPalette.WindowText, brush1)
        palette5.setBrush(QPalette.Disabled, QPalette.Text, brush1)
        self.labelMetadataLocation.setPalette(palette5)
        self.labelMetadataLocation.setFont(font4)
        self.labelMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameMetadataLocation, 4, 0, 1, 1)

        QWidget.setTabOrder(self.pushButtonReset, self.buttonChooseCloneListsLocation)
        QWidget.setTabOrder(self.buttonChooseCloneListsLocation, self.buttonChooseMetadataLocation)
        QWidget.setTabOrder(self.buttonChooseMetadataLocation, self.lineEditCloneListDownloadLocation)

        self.retranslateUi(Settings)

        QMetaObject.connectSlotsByName(Settings)
    # setupUi

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QCoreApplication.translate("Settings", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.pushButtonReset.setToolTip(QCoreApplication.translate("Settings", u"Reset all settings to default", None))
#endif // QT_CONFIG(tooltip)
        self.pushButtonReset.setText("")
        self.labelSettingsSaved.setText(QCoreApplication.translate("Settings", u"<html><head/><body><p>Settings are saved automatically.</p></body></html>", None))
        self.labelCloneListMetadataDownloadURL.setText(QCoreApplication.translate("Settings", u"Clone list and metadata download URL", None))
        self.labelURLError.setText(QCoreApplication.translate("Settings", u"URL isn't valid", None))
        self.labelDownloadLocations.setText(QCoreApplication.translate("Settings", u"Download locations", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseQuickImportLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where to recursively import DAT files from when the quick import button is pressed", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseQuickImportLocation.setText("")
        self.labelSelectQuickImportLocation.setText(QCoreApplication.translate("Settings", u"Quick import folder location", None))
        self.labelQuickImportLocation.setText(QCoreApplication.translate("Settings", u"No quick import folder selected", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseCloneListsLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the clone list folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseCloneListsLocation.setText("")
        self.labelSelectCloneListsLocation.setText(QCoreApplication.translate("Settings", u"Clone list folder location", None))
        self.labelCloneListsLocation.setText(QCoreApplication.translate("Settings", u"No clone list folder selected", None))
        self.labelPaths.setText(QCoreApplication.translate("Settings", u"Paths", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseMetadataLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the metadata folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseMetadataLocation.setText("")
        self.labelSelectMetadataLocation.setText(QCoreApplication.translate("Settings", u"Metadata folder location", None))
        self.labelMetadataLocation.setText(QCoreApplication.translate("Settings", u"No metadata folder selected", None))
    # retranslateUi

