# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'retool-settings.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QDialog, QFrame, QGridLayout,
    QHBoxLayout, QLabel, QLayout, QPushButton,
    QSizePolicy, QSpacerItem, QWidget)

from modules.gui.gui_widgets import (CustomLineEdit, ElisionLabel)
from . import resources_rc

class Ui_Settings(object):
    def setupUi(self, Settings):
        if not Settings.objectName():
            Settings.setObjectName(u"Settings")
        Settings.resize(604, 520)
        sizePolicy = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Settings.sizePolicy().hasHeightForWidth())
        Settings.setSizePolicy(sizePolicy)
        Settings.setMinimumSize(QSize(604, 520))
        Settings.setMaximumSize(QSize(604, 520))
        Settings.setAutoFillBackground(False)
        Settings.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.gridLayoutWidget = QWidget(Settings)
        self.gridLayoutWidget.setObjectName(u"gridLayoutWidget")
        self.gridLayoutWidget.setGeometry(QRect(-1, -1, 601, 524))
        self.gridLayout = QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setObjectName(u"gridLayout")
        self.gridLayout.setSizeConstraint(QLayout.SizeConstraint.SetMinAndMaxSize)
        self.gridLayout.setVerticalSpacing(10)
        self.gridLayout.setContentsMargins(15, 15, 15, 0)
        self.frameMetadataLocation = QFrame(self.gridLayoutWidget)
        self.frameMetadataLocation.setObjectName(u"frameMetadataLocation")
        sizePolicy1 = QSizePolicy(QSizePolicy.Policy.Preferred, QSizePolicy.Policy.Fixed)
        sizePolicy1.setHorizontalStretch(0)
        sizePolicy1.setVerticalStretch(0)
        sizePolicy1.setHeightForWidth(self.frameMetadataLocation.sizePolicy().hasHeightForWidth())
        self.frameMetadataLocation.setSizePolicy(sizePolicy1)
        self.frameMetadataLocation.setMinimumSize(QSize(0, 48))
        self.frameMetadataLocation.setMaximumSize(QSize(16777215, 48))
        self.frameMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameMetadataLocation.setFrameShape(QFrame.Shape.NoFrame)
        self.frameMetadataLocation.setFrameShadow(QFrame.Shadow.Plain)
        self.frameMetadataLocation.setLineWidth(0)
        self.buttonChooseMetadataLocation = QPushButton(self.frameMetadataLocation)
        self.buttonChooseMetadataLocation.setObjectName(u"buttonChooseMetadataLocation")
        self.buttonChooseMetadataLocation.setGeometry(QRect(0, 0, 44, 48))
        sizePolicy.setHeightForWidth(self.buttonChooseMetadataLocation.sizePolicy().hasHeightForWidth())
        self.buttonChooseMetadataLocation.setSizePolicy(sizePolicy)
        font = QFont()
        font.setPointSize(10)
        self.buttonChooseMetadataLocation.setFont(font)
        icon = QIcon()
        icon.addFile(u":/retoolFiles/images/icons8-live-folder-80.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.buttonChooseMetadataLocation.setIcon(icon)
        self.buttonChooseMetadataLocation.setIconSize(QSize(32, 32))
        self.buttonChooseMetadataLocation.setAutoDefault(False)
        self.labelSelectMetadataLocation = QLabel(self.frameMetadataLocation)
        self.labelSelectMetadataLocation.setObjectName(u"labelSelectMetadataLocation")
        self.labelSelectMetadataLocation.setGeometry(QRect(56, 0, 510, 22))
        font1 = QFont()
        font1.setBold(False)
        self.labelSelectMetadataLocation.setFont(font1)
        self.labelSelectMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelMetadataLocation = ElisionLabel(self.frameMetadataLocation)
        self.labelMetadataLocation.setObjectName(u"labelMetadataLocation")
        self.labelMetadataLocation.setGeometry(QRect(56, 20, 510, 20))
        palette = QPalette()
        brush = QBrush(QColor(119, 119, 119, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(0, 0, 0, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        brush2 = QBrush(QColor(120, 120, 120, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush2)
        self.labelMetadataLocation.setPalette(palette)
        font2 = QFont()
        font2.setPointSize(8)
        self.labelMetadataLocation.setFont(font2)
        self.labelMetadataLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameMetadataLocation, 5, 0, 1, 1)

        self.verticalSpacer = QSpacerItem(20, 10, QSizePolicy.Policy.Minimum, QSizePolicy.Policy.Fixed)

        self.gridLayout.addItem(self.verticalSpacer, 10, 0, 1, 1)

        self.horizontalLayout = QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName(u"horizontalLayout")
        self.horizontalLayout.setSizeConstraint(QLayout.SizeConstraint.SetDefaultConstraint)
        self.labelCloneListMetadataDownloadURL = QLabel(self.gridLayoutWidget)
        self.labelCloneListMetadataDownloadURL.setObjectName(u"labelCloneListMetadataDownloadURL")
        self.labelCloneListMetadataDownloadURL.setMinimumSize(QSize(0, 18))
        self.labelCloneListMetadataDownloadURL.setMaximumSize(QSize(16777215, 18))
        self.labelCloneListMetadataDownloadURL.setFont(font1)
        self.labelCloneListMetadataDownloadURL.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.horizontalLayout.addWidget(self.labelCloneListMetadataDownloadURL)

        self.labelURLError = QLabel(self.gridLayoutWidget)
        self.labelURLError.setObjectName(u"labelURLError")
        self.labelURLError.setMinimumSize(QSize(0, 18))
        self.labelURLError.setMaximumSize(QSize(16777215, 18))
        palette1 = QPalette()
        brush3 = QBrush(QColor(255, 0, 0, 255))
        brush3.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush3)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush1)
        palette1.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        self.labelURLError.setPalette(palette1)
        self.labelURLError.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelURLError.setAlignment(Qt.AlignmentFlag.AlignRight|Qt.AlignmentFlag.AlignTrailing|Qt.AlignmentFlag.AlignVCenter)

        self.horizontalLayout.addWidget(self.labelURLError)


        self.gridLayout.addLayout(self.horizontalLayout, 14, 0, 1, 1)

        self.frameRALocation = QFrame(self.gridLayoutWidget)
        self.frameRALocation.setObjectName(u"frameRALocation")
        sizePolicy1.setHeightForWidth(self.frameRALocation.sizePolicy().hasHeightForWidth())
        self.frameRALocation.setSizePolicy(sizePolicy1)
        self.frameRALocation.setMinimumSize(QSize(0, 48))
        self.frameRALocation.setMaximumSize(QSize(16777215, 48))
        self.frameRALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameRALocation.setFrameShape(QFrame.Shape.NoFrame)
        self.frameRALocation.setFrameShadow(QFrame.Shadow.Plain)
        self.frameRALocation.setLineWidth(0)
        self.buttonChooseRALocation = QPushButton(self.frameRALocation)
        self.buttonChooseRALocation.setObjectName(u"buttonChooseRALocation")
        self.buttonChooseRALocation.setGeometry(QRect(0, 0, 44, 48))
        sizePolicy.setHeightForWidth(self.buttonChooseRALocation.sizePolicy().hasHeightForWidth())
        self.buttonChooseRALocation.setSizePolicy(sizePolicy)
        self.buttonChooseRALocation.setFont(font)
        self.buttonChooseRALocation.setIcon(icon)
        self.buttonChooseRALocation.setIconSize(QSize(32, 32))
        self.buttonChooseRALocation.setAutoDefault(False)
        self.labelSelectRALocation = QLabel(self.frameRALocation)
        self.labelSelectRALocation.setObjectName(u"labelSelectRALocation")
        self.labelSelectRALocation.setGeometry(QRect(56, 0, 510, 22))
        self.labelSelectRALocation.setFont(font1)
        self.labelSelectRALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelRALocation = ElisionLabel(self.frameRALocation)
        self.labelRALocation.setObjectName(u"labelRALocation")
        self.labelRALocation.setGeometry(QRect(56, 20, 510, 20))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        palette2.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush2)
        self.labelRALocation.setPalette(palette2)
        self.labelRALocation.setFont(font2)
        self.labelRALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameRALocation, 7, 0, 1, 1)

        self.lineDownloadLocations = QFrame(self.gridLayoutWidget)
        self.lineDownloadLocations.setObjectName(u"lineDownloadLocations")
        palette3 = QPalette()
        brush4 = QBrush(QColor(85, 85, 85, 255))
        brush4.setStyle(Qt.BrushStyle.SolidPattern)
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush4)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush4)
        palette3.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        self.lineDownloadLocations.setPalette(palette3)
        self.lineDownloadLocations.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.lineDownloadLocations.setFrameShadow(QFrame.Shadow.Plain)
        self.lineDownloadLocations.setFrameShape(QFrame.Shape.HLine)

        self.gridLayout.addWidget(self.lineDownloadLocations, 12, 0, 1, 1)

        self.labelPaths = QLabel(self.gridLayoutWidget)
        self.labelPaths.setObjectName(u"labelPaths")
        self.labelPaths.setMinimumSize(QSize(0, 18))
        self.labelPaths.setMaximumSize(QSize(16777215, 18))
        font3 = QFont()
        font3.setBold(True)
        self.labelPaths.setFont(font3)
        self.labelPaths.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelPaths.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.gridLayout.addWidget(self.labelPaths, 1, 0, 1, 1)

        self.labelDownloadLocations = QLabel(self.gridLayoutWidget)
        self.labelDownloadLocations.setObjectName(u"labelDownloadLocations")
        self.labelDownloadLocations.setMinimumSize(QSize(0, 18))
        self.labelDownloadLocations.setMaximumSize(QSize(16777215, 18))
        self.labelDownloadLocations.setFont(font3)
        self.labelDownloadLocations.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelDownloadLocations.setTextInteractionFlags(Qt.TextInteractionFlag.NoTextInteraction)

        self.gridLayout.addWidget(self.labelDownloadLocations, 11, 0, 1, 1)

        self.frameCloneListsLocation = QFrame(self.gridLayoutWidget)
        self.frameCloneListsLocation.setObjectName(u"frameCloneListsLocation")
        sizePolicy1.setHeightForWidth(self.frameCloneListsLocation.sizePolicy().hasHeightForWidth())
        self.frameCloneListsLocation.setSizePolicy(sizePolicy1)
        self.frameCloneListsLocation.setMinimumSize(QSize(0, 48))
        self.frameCloneListsLocation.setMaximumSize(QSize(16777215, 48))
        self.frameCloneListsLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameCloneListsLocation.setFrameShape(QFrame.Shape.NoFrame)
        self.frameCloneListsLocation.setFrameShadow(QFrame.Shadow.Plain)
        self.frameCloneListsLocation.setLineWidth(0)
        self.buttonChooseCloneListsLocation = QPushButton(self.frameCloneListsLocation)
        self.buttonChooseCloneListsLocation.setObjectName(u"buttonChooseCloneListsLocation")
        self.buttonChooseCloneListsLocation.setGeometry(QRect(0, 0, 44, 48))
        sizePolicy.setHeightForWidth(self.buttonChooseCloneListsLocation.sizePolicy().hasHeightForWidth())
        self.buttonChooseCloneListsLocation.setSizePolicy(sizePolicy)
        self.buttonChooseCloneListsLocation.setFont(font)
        self.buttonChooseCloneListsLocation.setIcon(icon)
        self.buttonChooseCloneListsLocation.setIconSize(QSize(32, 32))
        self.buttonChooseCloneListsLocation.setAutoDefault(False)
        self.labelSelectCloneListsLocation = QLabel(self.frameCloneListsLocation)
        self.labelSelectCloneListsLocation.setObjectName(u"labelSelectCloneListsLocation")
        self.labelSelectCloneListsLocation.setGeometry(QRect(56, 0, 510, 16))
        self.labelSelectCloneListsLocation.setFont(font1)
        self.labelCloneListsLocation = ElisionLabel(self.frameCloneListsLocation)
        self.labelCloneListsLocation.setObjectName(u"labelCloneListsLocation")
        self.labelCloneListsLocation.setGeometry(QRect(56, 20, 510, 20))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush2)
        self.labelCloneListsLocation.setPalette(palette4)
        self.labelCloneListsLocation.setFont(font2)

        self.gridLayout.addWidget(self.frameCloneListsLocation, 4, 0, 1, 1)

        self.frameMIALocation = QFrame(self.gridLayoutWidget)
        self.frameMIALocation.setObjectName(u"frameMIALocation")
        sizePolicy1.setHeightForWidth(self.frameMIALocation.sizePolicy().hasHeightForWidth())
        self.frameMIALocation.setSizePolicy(sizePolicy1)
        self.frameMIALocation.setMinimumSize(QSize(0, 48))
        self.frameMIALocation.setMaximumSize(QSize(16777215, 48))
        self.frameMIALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameMIALocation.setFrameShape(QFrame.Shape.NoFrame)
        self.frameMIALocation.setFrameShadow(QFrame.Shadow.Plain)
        self.frameMIALocation.setLineWidth(0)
        self.buttonChooseMIALocation = QPushButton(self.frameMIALocation)
        self.buttonChooseMIALocation.setObjectName(u"buttonChooseMIALocation")
        self.buttonChooseMIALocation.setGeometry(QRect(0, 0, 44, 48))
        sizePolicy.setHeightForWidth(self.buttonChooseMIALocation.sizePolicy().hasHeightForWidth())
        self.buttonChooseMIALocation.setSizePolicy(sizePolicy)
        self.buttonChooseMIALocation.setFont(font)
        self.buttonChooseMIALocation.setIcon(icon)
        self.buttonChooseMIALocation.setIconSize(QSize(32, 32))
        self.buttonChooseMIALocation.setAutoDefault(False)
        self.labelSelectMIALocation = QLabel(self.frameMIALocation)
        self.labelSelectMIALocation.setObjectName(u"labelSelectMIALocation")
        self.labelSelectMIALocation.setGeometry(QRect(56, 0, 510, 22))
        self.labelSelectMIALocation.setFont(font1)
        self.labelSelectMIALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelMIALocation = ElisionLabel(self.frameMIALocation)
        self.labelMIALocation.setObjectName(u"labelMIALocation")
        self.labelMIALocation.setGeometry(QRect(56, 20, 510, 20))
        palette5 = QPalette()
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        palette5.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush2)
        self.labelMIALocation.setPalette(palette5)
        self.labelMIALocation.setFont(font2)
        self.labelMIALocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameMIALocation, 6, 0, 1, 1)

        self.linePaths = QFrame(self.gridLayoutWidget)
        self.linePaths.setObjectName(u"linePaths")
        palette6 = QPalette()
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush4)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush4)
        palette6.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        self.linePaths.setPalette(palette6)
        self.linePaths.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.linePaths.setFrameShadow(QFrame.Shadow.Plain)
        self.linePaths.setFrameShape(QFrame.Shape.HLine)

        self.gridLayout.addWidget(self.linePaths, 2, 0, 1, 1)

        self.frameResetButton = QFrame(self.gridLayoutWidget)
        self.frameResetButton.setObjectName(u"frameResetButton")
        self.frameResetButton.setMinimumSize(QSize(0, 25))
        self.frameResetButton.setMaximumSize(QSize(16777215, 25))
        self.frameResetButton.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameResetButton.setFrameShape(QFrame.Shape.NoFrame)
        self.frameResetButton.setFrameShadow(QFrame.Shadow.Plain)
        self.pushButtonReset = QPushButton(self.frameResetButton)
        self.pushButtonReset.setObjectName(u"pushButtonReset")
        self.pushButtonReset.setGeometry(QRect(546, -2, 25, 28))
        sizePolicy2 = QSizePolicy(QSizePolicy.Policy.Fixed, QSizePolicy.Policy.Preferred)
        sizePolicy2.setHorizontalStretch(0)
        sizePolicy2.setVerticalStretch(0)
        sizePolicy2.setHeightForWidth(self.pushButtonReset.sizePolicy().hasHeightForWidth())
        self.pushButtonReset.setSizePolicy(sizePolicy2)
        self.pushButtonReset.setMinimumSize(QSize(25, 28))
        self.pushButtonReset.setMaximumSize(QSize(25, 28))
        self.pushButtonReset.setLayoutDirection(Qt.LayoutDirection.LeftToRight)
        icon1 = QIcon()
        icon1.addFile(u":/retoolFiles/images/icons8-restart-80.png", QSize(), QIcon.Mode.Normal, QIcon.State.Off)
        self.pushButtonReset.setIcon(icon1)
        self.pushButtonReset.setAutoDefault(False)
        self.labelSettingsSaved = QLabel(self.frameResetButton)
        self.labelSettingsSaved.setObjectName(u"labelSettingsSaved")
        self.labelSettingsSaved.setGeometry(QRect(0, 0, 381, 18))
        self.labelSettingsSaved.setMinimumSize(QSize(0, 18))
        self.labelSettingsSaved.setMaximumSize(QSize(16777215, 18))
        font4 = QFont()
        self.labelSettingsSaved.setFont(font4)
        self.labelSettingsSaved.setScaledContents(False)
        self.labelSettingsSaved.setAlignment(Qt.AlignmentFlag.AlignLeading|Qt.AlignmentFlag.AlignLeft|Qt.AlignmentFlag.AlignTop)
        self.labelSettingsSaved.setWordWrap(True)
        self.labelSettingsSaved.setOpenExternalLinks(True)
        self.labelSettingsSaved.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByKeyboard|Qt.TextInteractionFlag.LinksAccessibleByMouse)

        self.gridLayout.addWidget(self.frameResetButton, 0, 0, 1, 1)

        self.frameCloneListMetadataDownloadLocation = QFrame(self.gridLayoutWidget)
        self.frameCloneListMetadataDownloadLocation.setObjectName(u"frameCloneListMetadataDownloadLocation")
        self.frameCloneListMetadataDownloadLocation.setMinimumSize(QSize(0, 24))
        self.frameCloneListMetadataDownloadLocation.setMaximumSize(QSize(16777215, 24))
        self.frameCloneListMetadataDownloadLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameCloneListMetadataDownloadLocation.setFrameShape(QFrame.Shape.StyledPanel)
        self.frameCloneListMetadataDownloadLocation.setFrameShadow(QFrame.Shadow.Raised)
        self.lineEditCloneListDownloadLocation = CustomLineEdit(self.frameCloneListMetadataDownloadLocation)
        self.lineEditCloneListDownloadLocation.setObjectName(u"lineEditCloneListDownloadLocation")
        self.lineEditCloneListDownloadLocation.setGeometry(QRect(0, 0, 571, 24))
        self.lineEditCloneListDownloadLocation.setMinimumSize(QSize(0, 24))
        self.lineEditCloneListDownloadLocation.setMaximumSize(QSize(16777215, 24))

        self.gridLayout.addWidget(self.frameCloneListMetadataDownloadLocation, 16, 0, 1, 1)

        self.frameQuickImportLocation = QFrame(self.gridLayoutWidget)
        self.frameQuickImportLocation.setObjectName(u"frameQuickImportLocation")
        sizePolicy1.setHeightForWidth(self.frameQuickImportLocation.sizePolicy().hasHeightForWidth())
        self.frameQuickImportLocation.setSizePolicy(sizePolicy1)
        self.frameQuickImportLocation.setMinimumSize(QSize(0, 48))
        self.frameQuickImportLocation.setMaximumSize(QSize(16777215, 48))
        self.frameQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.frameQuickImportLocation.setFrameShape(QFrame.Shape.NoFrame)
        self.frameQuickImportLocation.setFrameShadow(QFrame.Shadow.Plain)
        self.frameQuickImportLocation.setLineWidth(0)
        self.buttonChooseQuickImportLocation = QPushButton(self.frameQuickImportLocation)
        self.buttonChooseQuickImportLocation.setObjectName(u"buttonChooseQuickImportLocation")
        self.buttonChooseQuickImportLocation.setGeometry(QRect(0, 0, 44, 48))
        sizePolicy.setHeightForWidth(self.buttonChooseQuickImportLocation.sizePolicy().hasHeightForWidth())
        self.buttonChooseQuickImportLocation.setSizePolicy(sizePolicy)
        self.buttonChooseQuickImportLocation.setFont(font)
        self.buttonChooseQuickImportLocation.setIcon(icon)
        self.buttonChooseQuickImportLocation.setIconSize(QSize(32, 32))
        self.buttonChooseQuickImportLocation.setAutoDefault(False)
        self.labelSelectQuickImportLocation = QLabel(self.frameQuickImportLocation)
        self.labelSelectQuickImportLocation.setObjectName(u"labelSelectQuickImportLocation")
        self.labelSelectQuickImportLocation.setGeometry(QRect(56, 0, 510, 22))
        self.labelSelectQuickImportLocation.setFont(font1)
        self.labelSelectQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))
        self.labelQuickImportLocation = ElisionLabel(self.frameQuickImportLocation)
        self.labelQuickImportLocation.setObjectName(u"labelQuickImportLocation")
        self.labelQuickImportLocation.setGeometry(QRect(56, 20, 510, 20))
        palette7 = QPalette()
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Text, brush1)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Text, brush1)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.WindowText, brush2)
        palette7.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Text, brush2)
        self.labelQuickImportLocation.setPalette(palette7)
        self.labelQuickImportLocation.setFont(font2)
        self.labelQuickImportLocation.setLocale(QLocale(QLocale.English, QLocale.UnitedStates))

        self.gridLayout.addWidget(self.frameQuickImportLocation, 3, 0, 1, 1)

        QWidget.setTabOrder(self.pushButtonReset, self.buttonChooseCloneListsLocation)
        QWidget.setTabOrder(self.buttonChooseCloneListsLocation, self.buttonChooseMetadataLocation)
        QWidget.setTabOrder(self.buttonChooseMetadataLocation, self.lineEditCloneListDownloadLocation)

        self.retranslateUi(Settings)

        QMetaObject.connectSlotsByName(Settings)
    # setupUi

    def retranslateUi(self, Settings):
        Settings.setWindowTitle(QCoreApplication.translate("Settings", u"Settings", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseMetadataLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the metadata folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseMetadataLocation.setText("")
        self.labelSelectMetadataLocation.setText(QCoreApplication.translate("Settings", u"Metadata folder location", None))
        self.labelMetadataLocation.setText(QCoreApplication.translate("Settings", u"No metadata folder selected", None))
        self.labelCloneListMetadataDownloadURL.setText(QCoreApplication.translate("Settings", u"Clone list and metadata download URL", None))
        self.labelURLError.setText(QCoreApplication.translate("Settings", u"URL isn't valid", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseRALocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the MIA folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseRALocation.setText("")
        self.labelSelectRALocation.setText(QCoreApplication.translate("Settings", u"RetroAchievements folder location", None))
        self.labelRALocation.setText(QCoreApplication.translate("Settings", u"No RetroAchievements folder selected", None))
        self.labelPaths.setText(QCoreApplication.translate("Settings", u"Paths", None))
        self.labelDownloadLocations.setText(QCoreApplication.translate("Settings", u"Download locations", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseCloneListsLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the clone list folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseCloneListsLocation.setText("")
        self.labelSelectCloneListsLocation.setText(QCoreApplication.translate("Settings", u"Clone list folder location", None))
        self.labelCloneListsLocation.setText(QCoreApplication.translate("Settings", u"No clone list folder selected", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseMIALocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where the MIA folder is located", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseMIALocation.setText("")
        self.labelSelectMIALocation.setText(QCoreApplication.translate("Settings", u"MIA folder location", None))
        self.labelMIALocation.setText(QCoreApplication.translate("Settings", u"No MIA folder selected", None))
#if QT_CONFIG(tooltip)
        self.pushButtonReset.setToolTip(QCoreApplication.translate("Settings", u"Reset all settings to default", None))
#endif // QT_CONFIG(tooltip)
        self.pushButtonReset.setText("")
        self.labelSettingsSaved.setText(QCoreApplication.translate("Settings", u"<html><head/><body><p>Settings are saved automatically.</p></body></html>", None))
#if QT_CONFIG(tooltip)
        self.buttonChooseQuickImportLocation.setToolTip(QCoreApplication.translate("Settings", u"Choose where to recursively import DAT files from when the quick import button is pressed", None))
#endif // QT_CONFIG(tooltip)
        self.buttonChooseQuickImportLocation.setText("")
        self.labelSelectQuickImportLocation.setText(QCoreApplication.translate("Settings", u"Quick import folder location", None))
        self.labelQuickImportLocation.setText(QCoreApplication.translate("Settings", u"No quick import folder selected", None))
    # retranslateUi

